In [413]:
import pandas as pd
import numpy as np

22.12기준 인구집계현황 데이터 - 인구소멸 위기지역 Top10 구하기

- 기초자치단체(시, 군)
특례시: 수원, 고양, 용인(구)
행정구: 성남, 안산, 안양(구)

In [414]:
df = pd.read_csv('data/주민등록인구집계현황.csv',encoding='euc=kr')
df.head(1)

,연도,월,행정구역구분명,행정구역명,총 인구수,0~9세,10~19세,20~29세,30~39세,40~49세,...,10~19세 (여),20~29세 (여),30~39세 (여),40~49세 (여),50~59세 (여),60~69세 (여),70~79세 (여),80~89세 (여),90~99세 (여),100세 이상 (여)
0,2022,12,도,경기도,13589432,1040954,1327726,1737291,1882300,2284603,...,647283,821150,904073,1121889,1133428,878494,437251,252711,44184,1369

In [415]:
# 카테고리 정리/ 셀렉
df = df[['행정구역구분명','행정구역명','20~29세 (여)','30~39세 (여)','60~69세','70~79세','80~89세','90~99세','100세 이상']]
df.set_index('행정구역구분명', inplace=True)
df.drop('읍면동', inplace=True)

df.head()

,행정구역명,20~29세 (여),30~39세 (여),60~69세,70~79세,80~89세,90~99세,100세 이상
행정구역구분명,,,,,,,,
도,경기도,821150,904073,1750962,808663,403721,58065,1725
시군,경기도 가평군,2503,2433,13315,7082,3999,564,19
시군,경기도 고양시,69028,71491,140266,62941,37677,5480,145
구,경기도 고양시 덕양구,29600,35039,65372,31304,17384,2321,58
구,경기도 고양시 일산동구,20570,19146,38362,15846,9838,1587,41

In [416]:
# 노령화 비율 구하기
df['가임기여성수'] = df['20~29세 (여)'] + df['30~39세 (여)']
df['노령인구'] = df.loc[:, '60~69세':'100세 이상'].sum(axis=1)

df['노령화비율'] = df['가임기여성수'] / df['노령인구']
df.head(2)

,행정구역명,20~29세 (여),30~39세 (여),60~69세,70~79세,80~89세,90~99세,100세 이상,가임기여성수,노령인구,노령화비율
행정구역구분명,,,,,,,,,,,
도,경기도,821150,904073,1750962,808663,403721,58065,1725,1725223,3023136,0.570673
시군,경기도 가평군,2503,2433,13315,7082,3999,564,19,4936,24979,0.197606

In [417]:
df=df[['행정구역명','가임기여성수','노령인구','노령화비율']]
df.head(2)

            행정구역명   가임기여성수     노령인구     노령화비율
행정구역구분명
도           경기도    1725223  3023136  0.570673
시군       경기도 가평군      4936    24979  0.197606

In [418]:
# 도, 특례시, 광역시 데이터 제거하기(~시로 끝나는 데이터만 필터링 .str.endswith() )

# df['행정구역'] = df['행정구역명'].str.split(" ", expand=True)         # # 행정구역명 str으로 만들고, 분할된 개별 리스트를 데이터 프레임으로 전환
# df[df['행정구역'].endswith("시")]
df['행정구역'] = df['행정구역명'].str.findall('\w+도')

# df.drop(index= df[df['행정구역']])

df.head()

                 행정구역명   가임기여성수     노령인구     노령화비율   행정구역
행정구역구분명
도                경기도    1725223  3023136  0.570673  [경기도]
시군            경기도 가평군      4936    24979  0.197606  [경기도]
시군            경기도 고양시    140519   246509  0.570036  [경기도]
구         경기도 고양시 덕양구     64639   116439  0.555132  [경기도]
구        경기도 고양시 일산동구     39716    65674  0.604745  [경기도]

In [419]:
df.sort_values(by='노령화비율').head(1)

            행정구역명  가임기여성수   노령인구     노령화비율   행정구역
행정구역구분명
시군       경기도 가평군     4936  24979  0.197606  [경기도]